### ISSUE TITLE
Check compatibility of Library 1 with Android example project (Library 1)

### ISSUE THREAD

**Issue by lukas-monet** [amosproj/amos2023ws03-gui-frame-diff#58]
## User story
1. As a user
2. I want to make sure that all dependencies that are used in Library1 are also working with Android
3. So that I can integrate the Library into my Android project

## Acceptance criteria
* all dependencies of Library 1 run with the android example project
* no build errors are shown when using Library 1 with android example

**Comment by a-miscellaneous** [comment]
Check dependencies of the first lib in android. 
Either get a local version of the lib or use a different lib

**Comment by fs3itz** [comment]
FATAL EXCEPTION: main
	Process: de.guiframediff.videogeneratorexample, PID: 7028
	java.lang.NoClassDefFoundError: org.bytedeco.ffmpeg.global.avutil
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.ffmpeg.avformat.Write_packet_Pointer_BytePointer_int.<clinit>(Write_packet_Pointer_BytePointer_int.java:21)
	at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:350)
	at VideoGeneratorImpl.processFrames(VideoGeneratorImpl.kt:33)
	at de.guiframediff.videogeneratorexample.MainActivity$onCreate$2$1.run(MainActivity.kt:41)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniavutil.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1226)
	at org.bytedeco.javacv.FFmpegFrameRecorder.tryLoad(FFmpegFrameRecorder.java:112)
	at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:138)
	at VideoGeneratorImpl.processFrames(VideoGeneratorImpl.kt:33) 
	at de.guiframediff.videogeneratorexample.MainActivity$onCreate$2$1.run(MainActivity.kt:41) 
	at android.os.Handler.handleCallback(Handler.java:958) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:294) 
	at android.app.ActivityThread.main(ActivityThread.java:8177) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
Caused by: java.lang.UnsatisfiedLinkError: Could not find jniavutil in class, module, and library paths.
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1799)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423) 
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234) 
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210) 
	at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14) 
	at java.lang.Class.classForName(Native Method) 
	at java.lang.Class.forName(Class.java:536) 
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289) 
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234) 
	at org.bytedeco.javacpp.Loader.load(Loader.java:1226) 
	at org.bytedeco.javacv.FFmpegFrameRecorder.tryLoad(FFmpegFrameRecorder.java:112) 
	at org.bytedeco.javacv.FFmpegFrameRecorder.<clinit>(FFmpegFrameRecorder.java:138) 
	at VideoGeneratorImpl.processFrames(VideoGeneratorImpl.kt:33) 
	at de.guiframediff.videogeneratorexample.MainActivity$onCreate$2$1.run(MainActivity.kt:41) 
	at android.os.Handler.handleCallback(Handler.java:958) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:294) 
	at android.app.ActivityThread.main(ActivityThread.java:8177) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by fs3itz** [comment]
This could help:
[https://stackoverflow.com/questions/75817027/how-to-set-up-javacv-for-android-studio](https://stackoverflow.com/questions/75817027/how-to-set-up-javacv-for-android-studio)

**Comment by zino212** [comment]
I am quite confused now. Based on the error that causes the app to crash, there is some native library missing.
Gradle should download and package these libraries automatically when building the app. Apparently this doesn't happen.
The different 'tips and fixes' I found als did not change a thing.
Maybe I am just not seeing the obvious solution ...
